version: 1

formatters:
  brief:
    format: "%(message)s"
  precise:
    format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: ./logs/info.log
    maxBytes: 1024
    backupCount: 3
loggers:
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  uvicorn.error:
    level: DEBUG
    handlers: [console, file]
    propagate: no
