services:
  postgresql:
    extends:
      file: docker-compose.yml
      service: postgresql
    ports:
      - "5432:5432"

  chroma:
    extends:
      file: docker-compose.yml
      service: chroma
    ports:
      - "8000:8000"

  iada:
    extends:
      file: docker-compose.yml
      service: iada
    build:
      context: ./docker/iada
