x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: [*restart_policy]

  chroma:
    image: chromadb/chroma:0.5.4
    volumes:
      - ./storage/chroma:/chroma/chroma
    <<: [*restart_policy]

  iada:
    build:
      context: ./docker/iada
    ports:
      - "${PORT}:80"
    depends_on:
      - postgresql
      - chroma
    <<: [*restart_policy]
