services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ./data/ollama:/root/.ollama

  chroma:
    image: chromadb/chroma
    restart: always
    volumes:
      - ./data/chroma:/chroma/chroma
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api

  api:
    build:
      context: ./docker/api
    restart: always
    environment:
      OLLAMA_MODEL: llama3
      #OLLAMA_URL: http://ollama:11434
      OLLAMA_URL: http://host.docker.internal:11434
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      CHROMA_URL: http://chroma:8000
    depends_on:
      - db
      - chroma
      - ollama

  web:
    build:
      context: ./docker/web
    restart: always
