services:
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chroma:
    image: chromadb/chroma
    restart: unless-stopped
    volumes:
      - ./storage/chroma:/chroma/chroma

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - chat-frontend
      - chat-backend

  chat-backend:
    build:
      context: ./chat/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      CHROMA_URL: http://chroma:8000
    depends_on:
      - postgresql
      - chroma

  chat-frontend:
    build:
      context: ./chat/frontend
    volumes:
      - ./www/chat:/app/dist
